import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET() {
    try {
        const settings = await prisma.siteSetting.findUnique({
            where: { id: 'main' },
        });
        return NextResponse.json(settings || {});
    } catch (error) {
        return NextResponse.json({ error: 'Failed to fetch settings' }, { status: 500 });
    }
}

export async function POST(request: Request) {
    try {
        const data = await request.json();

        // Simple authentication/authorization guard could be added here

        const settings = await prisma.siteSetting.upsert({
            where: { id: 'main' },
            update: {
                hotelName: data.hotelName,
                address: data.address,
                heroTitle: data.heroTitle,
                heroSubtitle: data.heroSubtitle,
                heroImage: data.heroImage,
                aboutText: data.aboutText,
                contactPhone: data.contactPhone,
                contactEmail: data.contactEmail,
                aboutHero: data.aboutHero,
                aboutVision: data.aboutVision,
                aboutStory: data.aboutStory,
                facebookUrl: data.facebookUrl,
                instagramUrl: data.instagramUrl,
                twitterUrl: data.twitterUrl,
                youtubeUrl: data.youtubeUrl,
                tiktokUrl: data.tiktokUrl,
                seoKeywords: data.seoKeywords,
                seoDescription: data.seoDescription,
                spiritImage: data.spiritImage,
                spiritHeading: data.spiritHeading,
                spiritLabel: data.spiritLabel,
                footerBadge: data.footerBadge,
                footerDescription: data.footerDescription,
                bookingLink: data.bookingLink,
                logoUrl: data.logoUrl,
                logoAlt: data.logoAlt,
                journalHeroLabel: data.journalHeroLabel,
                journalHeroTitle: data.journalHeroTitle,
                journalHeroDescription: data.journalHeroDescription,
                aboutHeroImage: data.aboutHeroImage,
                aboutVisionImage1: data.aboutVisionImage1,
                aboutVisionImage2: data.aboutVisionImage2,
                apartmentsHeroImage: data.apartmentsHeroImage,
                contactHeroImage: data.contactHeroImage,
                journalHeroImage: data.journalHeroImage,
                suitesHeading: data.suitesHeading,
                suitesDescription: data.suitesDescription,
                amenitiesHeading: data.amenitiesHeading,
                amenitiesDescription: data.amenitiesDescription,
                amenitiesSubtitle: data.amenitiesSubtitle,
                experienceTitle: data.experienceTitle,
                experienceLabel: data.experienceLabel,
                aboutLeadershipHeading: data.aboutLeadershipHeading,
                aboutLeadershipDescription: data.aboutLeadershipDescription,
                apartmentsHeroLabel: data.apartmentsHeroLabel,
                apartmentsHeroTitle: data.apartmentsHeroTitle,
                apartmentsHeroDescription: data.apartmentsHeroDescription,
                contactHeroLabel: data.contactHeroLabel,
                contactHeroTitle: data.contactHeroTitle,
                contactHeroDescription: data.contactHeroDescription,
                contactFormHeading: data.contactFormHeading,
                contactFormDescription: data.contactFormDescription,
                aboutHeroLabel: data.aboutHeroLabel,
                aboutPillarsLabel: data.aboutPillarsLabel,
                aboutPillarsHeading: data.aboutPillarsHeading,
                amenitiesImage: data.amenitiesImage,
                seoImage: data.seoImage,
                contactMapUrl: data.contactMapUrl,
                contactHoursWeekday: data.contactHoursWeekday,
                contactHoursSaturday: data.contactHoursSaturday,
                contactHoursSunday: data.contactHoursSunday,
                contactHoursReception: data.contactHoursReception,
                contactCallHeading: data.contactCallHeading,
                contactCallDescription: data.contactCallDescription,
                contactCallButtonText: data.contactCallButtonText,
                contactCallButtonLink: data.contactCallButtonLink,
            },
            create: {
                id: 'main',
                hotelName: data.hotelName || "NL Josephine's Hotel & Apt",
                address: data.address || "Seguku, Entebbe Road\\nKampala, Uganda",
                heroTitle: data.heroTitle || 'Welcome',
                heroSubtitle: data.heroSubtitle || '',
                heroImage: data.heroImage || '',
                aboutText: data.aboutText || '',
                contactPhone: data.contactPhone || '',
                contactEmail: data.contactEmail || '',
                aboutHero: data.aboutHero || "More Than a Residence.\\nNL Josephine's Hotel & Apt.",
                aboutVision: data.aboutVision || 'Born from a desire to blend uncompromising tranquility with modern luxury.',
                aboutStory: data.aboutStory || "NL Josephine's Hotel & Apt was designed as a retreat from the ordinary. We believe that a home is not just a place, but a feeling—a serene haven where life's best moments unfold.\n\nEvery detail, from the grand architecture to the finest interior finishes, has been meticulously curated to foster an environment of peace, security, and absolute comfort for our residents.",
                facebookUrl: data.facebookUrl || "https://facebook.com",
                instagramUrl: data.instagramUrl || "https://instagram.com",
                twitterUrl: data.twitterUrl || "https://twitter.com",
                youtubeUrl: data.youtubeUrl || "https://youtube.com",
                tiktokUrl: data.tiktokUrl || "https://tiktok.com",
                seoKeywords: data.seoKeywords || "vacation rental, serviced apartments, luxury hotel, Entebbe, Uganda",
                seoDescription: data.seoDescription || "NL Josephine's Hotel & Apt offers uncompromising tranquility with modern luxury in Seguku, Entebbe Road.",
                spiritImage: data.spiritImage || "https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=2600&auto=format&fit=crop",
                spiritHeading: data.spiritHeading || "The Spirit of NL Josephine's Hotel & Apt",
                spiritLabel: data.spiritLabel || "Our Heritage",
                footerBadge: data.footerBadge || "A Haven",
                footerDescription: data.footerDescription || "Experience quiet luxury and uncompromising comfort. Your serene home away from home in the heart of Seguku.",
                bookingLink: data.bookingLink || "",
                logoUrl: data.logoUrl || "",
                logoAlt: data.logoAlt || "NL Josephine's Hotel & Apt Logo",
                journalHeroLabel: data.journalHeroLabel || "Our Stories",
                journalHeroTitle: data.journalHeroTitle || "The Journal",
                journalHeroDescription: data.journalHeroDescription || "Stay updated with the latest happenings, exclusive offers, and stories from our haven.",
                aboutHeroImage: data.aboutHeroImage || "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80",
                aboutVisionImage1: data.aboutVisionImage1 || "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80",
                aboutVisionImage2: data.aboutVisionImage2 || "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80",
                apartmentsHeroImage: data.apartmentsHeroImage || "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80",
                contactHeroImage: data.contactHeroImage || "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80",
                journalHeroImage: data.journalHeroImage || "https://images.unsplash.com/photo-1455391704245-2376bb74b358?auto=format&fit=crop&q=80",
                suitesHeading: data.suitesHeading || "Distinctive Suites",
                suitesDescription: data.suitesDescription || "Our most exclusive accommodations, individually curated to offer exceptional comfort, blending modern aesthetics with thoughtful amenities.",
                amenitiesHeading: data.amenitiesHeading || "Curated Amenities",
                amenitiesDescription: data.amenitiesDescription || "We believe true luxury lies in the details. Discover a thoughtful collection of amenities designed to elevate every moment of your stay with us.",
                amenitiesSubtitle: data.amenitiesSubtitle || "The Experience",
                experienceTitle: data.experienceTitle || "Everything you need, beautifully anticipated.",
                experienceLabel: data.experienceLabel || "Our Heritage",
                aboutLeadershipHeading: data.aboutLeadershipHeading || "The People Behind The Haven",
                aboutLeadershipDescription: data.aboutLeadershipDescription || "A dedicated team of professionals committed to delivering an exceptional living experience.",
                apartmentsHeroLabel: data.apartmentsHeroLabel || "The Collection",
                apartmentsHeroTitle: data.apartmentsHeroTitle || "Our Accommodations",
                apartmentsHeroDescription: data.apartmentsHeroDescription || "Discover our exclusive collection of premium, fully-serviced apartments designed for ultimate comfort and tranquility in the heart of Seguku.",
                contactHeroLabel: data.contactHeroLabel || "Get in Touch",
                contactHeroTitle: data.contactHeroTitle || "Welcome To NL Josephine's Hotel",
                contactHeroDescription: data.contactHeroDescription || "Whether you're planning a stay, have a question about our suites, or simply want to say hello — our concierge team is always ready.",
                contactFormHeading: data.contactFormHeading || "Send an Enquiry",
                contactFormDescription: data.contactFormDescription || "Our team will personally respond within 24 hours.",
                aboutHeroLabel: data.aboutHeroLabel || "Our Heritage",
                aboutPillarsLabel: data.aboutPillarsLabel || "The Foundation",
                aboutPillarsHeading: data.aboutPillarsHeading || "Our Core Pillars",
                amenitiesImage: data.amenitiesImage || "https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=2600&auto=format&fit=crop",
                seoImage: data.seoImage || "https://images.unsplash.com/photo-1542314831-c6a4d14d8343?q=80&w=2600&auto=format&fit=crop",
                contactMapUrl: data.contactMapUrl || "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.7547316428!2d32.5618!3d0.2717!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMCcx十八LjgiTiAzMsKwMzMnNDIuNSJF!5e0!3m2!1sen!2sug!4v1620000000000!5m2!1sen!2sug",
                contactHoursWeekday: data.contactHoursWeekday || "8:00 AM – 9:00 PM",
                contactHoursSaturday: data.contactHoursSaturday || "9:00 AM – 8:00 PM",
                contactHoursSunday: data.contactHoursSunday || "10:00 AM – 6:00 PM",
                contactHoursReception: data.contactHoursReception || "Open 24 / 7",
                contactCallHeading: data.contactCallHeading || "Prefer to call?",
                contactCallDescription: data.contactCallDescription || "Our team is always delighted to assist over a direct call.",
                contactCallButtonText: data.contactCallButtonText || "0772560696",
                contactCallButtonLink: data.contactCallButtonLink || "tel:+256772560696",
            },
        });

        return NextResponse.json({ message: 'Settings updated successfully', settings });
    } catch (error) {
        console.error('API Error:', error);
        return NextResponse.json({ error: 'Failed to update settings' }, { status: 500 });
    }
}
